"""Read a markdown document, name the paths inside it, and write generated files.

The renderer and the jobs that project this configuration onto other formats
both split a rule body at its frontmatter, resolve the paths it cites, and
write a generated file only where the content differs. That work sits here so
one definition serves both, and so nothing under this plugin has to import a
job that lives outside it.

Every function here reads or writes text. Which directory holds the bodies is
the caller's to name, so moving the corpus changes no line below.
"""

from __future__ import annotations

import dataclasses
import os
import re
import subprocess
from pathlib import Path

import yaml

HOME = Path.home()

# Where generated content names a path, it names it through these rather than
# through HOME, so no generated byte carries the account the generator ran under.
HOME_VAR = "$HOME"
CLAUDE_HOME_VAR = f"{HOME_VAR}/.claude"


@dataclasses.dataclass(frozen=True)
class Document:
    """A markdown file split at its YAML frontmatter.

    `frontmatter` is None when the file opens on something other than a
    `---` line, which distinguishes a file carrying no frontmatter from one
    carrying an empty mapping.
    """

    frontmatter: dict | None
    body: str


FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)


def parse_document(text: str) -> Document:
    match = FRONTMATTER.match(text)
    if match is None:
        return Document(frontmatter=None, body=text)
    return Document(
        frontmatter=yaml.safe_load(match.group(1)) or {},
        body=text[match.end() :].lstrip("\n"),
    )


MARKDOWN_LINK = re.compile(r"(?<=\]\()([^)\s]+)(?=\))")
SCHEME = re.compile(r"\A[a-zA-Z][a-zA-Z0-9+.-]*:")


def _absolute_link_target(target: str) -> str:
    if target.startswith(("#", "/", "~", "$")) or SCHEME.match(target):
        return target
    return os.path.normpath(os.path.join(CLAUDE_HOME_VAR, target))


def rewrite_paths(text: str) -> str:
    """Resolve the path references that only work from inside `~/.claude`.

    Generated files sit in directories where `~` goes unexpanded and where a
    link relative to `~/.claude` points at nothing. Both forms resolve against
    `$HOME`, which names the same directory on any account; every other byte
    survives.
    """

    text = MARKDOWN_LINK.sub(lambda m: _absolute_link_target(m.group(1)), text)
    return text.replace("~/", f"{HOME_VAR}/")


def _relative_link_target(target: str) -> str:
    if not target.startswith(f"{HOME_VAR}/"):
        return target
    relative = os.path.relpath(target, CLAUDE_HOME_VAR)
    return relative if relative.startswith("..") else f"./{relative}"


def restore_paths(text: str) -> str:
    """Undo `rewrite_paths`, one inverse per step and in the same order.

    A source file sits inside `~/.claude`, where `~` expands and a link
    resolves against that directory. `_absolute_link_target` maps `./x`,
    `x`, and `~/.claude/x` onto one target, so this picks the `./` form,
    which is the one the sources carry.
    """

    text = MARKDOWN_LINK.sub(lambda m: _relative_link_target(m.group(1)), text)
    return text.replace(f"{HOME_VAR}/", "~/")


def all_rules(rules_dir: Path) -> list[Path]:
    """Every rule file, sorted by filename."""

    return sorted(rules_dir.glob("*.md"))


def unconditional_rules(rules_dir: Path) -> list[Path]:
    """The rule files that load every session, carrying no frontmatter.

    A rule carrying `paths:` frontmatter stays out. Claude Code loads one
    only once a matching file enters play, and each adapter reproduces that
    condition from the same frontmatter, so listing it here would put the
    text in every prompt and a second copy in a matching one.
    """

    return [
        rule
        for rule in all_rules(rules_dir)
        if parse_document(rule.read_text(encoding="utf-8")).frontmatter is None
    ]


def ordered_rules(rules_dir: Path, order: tuple[str, ...]) -> list[Path]:
    """The unconditional rules in the given order.

    Raises ValueError naming every stem the order and the directory disagree
    on, so a new rule lands in the order before a run silently drops it.
    """

    present = {rule.stem: rule for rule in unconditional_rules(rules_dir)}
    unlisted = sorted(set(present) - set(order))
    absent = [stem for stem in order if stem not in present]
    if unlisted or absent:
        raise ValueError(
            f"working rules order disagrees with {rules_dir}: unlisted {unlisted}, absent {absent}"
        )
    return [present[stem] for stem in order]


def home_relative(path: Path) -> str:
    """`~/`-prefixed where the path sits under the home directory, absolute otherwise."""

    return f"~/{path.relative_to(HOME)}" if path.is_relative_to(HOME) else str(path)


def uncommitted(repo: Path, paths: list[Path]) -> list[str]:
    """Whichever of `paths` git reports as changed in `repo`.

    A directory outside any git repository reports none, so a run still
    works where nobody versions the configuration.
    """

    if not paths:
        return []
    finished = subprocess.run(
        ["git", "-C", str(repo), "status", "--porcelain", "--", *(str(path) for path in paths)],
        capture_output=True,
        text=True,
        check=False,
    )
    if finished.returncode != 0:
        return []

    changed = []
    for line in finished.stdout.splitlines():
        # Porcelain v1 gives two status characters, a space, then the path,
        # and a rename gives "old -> new", where the new name is the target.
        named = line[3:]
        _, _, renamed = named.partition(" -> ")
        changed.append(renamed or named)
    return changed


def refuse_uncommitted(repo: Path, paths: list[Path]) -> None:
    """Stop a run that would write over changes nobody has committed.

    Each direction overwrites the side it writes to whole, so a target
    carrying an edit git has never seen loses that edit with no diff to
    recover it from.
    """

    changed = uncommitted(repo, paths)
    if changed:
        raise ValueError(
            "these carry uncommitted changes this run would overwrite: "
            + ", ".join(changed)
            + ". Commit them and run again."
        )


@dataclasses.dataclass(frozen=True)
class GeneratedFile:
    path: Path
    content: str


def _current(path: Path) -> str | None:
    return path.read_text(encoding="utf-8") if path.is_file() else None


def write_or_check(files: tuple[GeneratedFile, ...], *, check: bool) -> int:
    """How many of `files` differ from what is on disk, named one per line.

    With `check` the count is all this does, so a caller reporting drift
    writes nothing. Otherwise each differing file gets written and reported
    with the byte counts it moved between.
    """

    stale = 0
    for generated in files:
        current = _current(generated.path)
        if current == generated.content:
            continue
        stale += 1
        if check:
            state = "missing" if current is None else "stale"
            print(f"{state}: {generated.path}")
            continue
        generated.path.parent.mkdir(parents=True, exist_ok=True)
        generated.path.write_text(generated.content, encoding="utf-8")
        if current is None:
            print(f"created: {generated.path} ({len(generated.content.encode())} bytes)")
        else:
            print(
                f"updated: {generated.path} "
                f"({len(current.encode())} -> {len(generated.content.encode())} bytes)"
            )
    return stale


def summarize(stale: int, total: int, *, check: bool) -> int:
    """Print the one line a gate reads, and answer the exit status.

    A caller writing files and a caller checking them report through this,
    so the pre-push gate reads one sentence whichever ran and a run that
    also owns JSON keys still prints one summary rather than two.
    """

    if check:
        print(f"{stale} of {total} generated outputs out of date")
        return 1 if stale else 0
    print(f"{stale} of {total} generated outputs written")
    return 0
