"""Shared ground for the jobs that project this checkout onto other formats.

Each job under this directory reads its sources through this module and
writes through its plan machinery, so a change to one job reaches no other
job's output. The jobs import this by name, since a script run by path puts
its own directory first on `sys.path`.

The directory the always-on rule bodies come from is named here once, as
`RULES_DIRNAME`, and every job reads it through `Targets.rules_dir`. Moving
that directory is a change to that one name.
"""

from __future__ import annotations

import dataclasses
import json
import os
import re
import subprocess
from pathlib import Path

import yaml

HOME = Path.home()

# The checkout this directory sits in, so a run reads and writes the tree it
# was invoked from and a hook inside a worktree syncs that worktree.
SCRIPT_ROOT = Path(__file__).resolve().parents[2]

# Where generated content names a path, it names it through these rather than
# through HOME, so no generated byte carries the account the generator ran under.
HOME_VAR = "$HOME"
CLAUDE_HOME_VAR = f"{HOME_VAR}/.claude"


@dataclasses.dataclass(frozen=True)
class Document:
    """A markdown file split at its YAML frontmatter.

    `frontmatter` is None when the file opens on something other than a
    `---` line, which distinguishes a file carrying no frontmatter from one
    carrying an empty mapping.
    """

    frontmatter: dict | None
    body: str


FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)


def parse_document(text: str) -> Document:
    match = FRONTMATTER.match(text)
    if match is None:
        return Document(frontmatter=None, body=text)
    return Document(
        frontmatter=yaml.safe_load(match.group(1)) or {},
        body=text[match.end() :].lstrip("\n"),
    )


MARKDOWN_LINK = re.compile(r"(?<=\]\()([^)\s]+)(?=\))")
SCHEME = re.compile(r"\A[a-zA-Z][a-zA-Z0-9+.-]*:")


def _absolute_link_target(target: str) -> str:
    if target.startswith(("#", "/", "~", "$")) or SCHEME.match(target):
        return target
    return os.path.normpath(os.path.join(CLAUDE_HOME_VAR, target))


def rewrite_paths(text: str) -> str:
    """Resolve the path references that only work from inside `~/.claude`.

    Generated files sit in directories where `~` goes unexpanded and where a
    link relative to `~/.claude` points at nothing. Both forms resolve against
    `$HOME`, which names the same directory on any account; every other byte
    survives.
    """

    text = MARKDOWN_LINK.sub(lambda m: _absolute_link_target(m.group(1)), text)
    return text.replace("~/", f"{HOME_VAR}/")


def _relative_link_target(target: str) -> str:
    if not target.startswith(f"{HOME_VAR}/"):
        return target
    relative = os.path.relpath(target, CLAUDE_HOME_VAR)
    return relative if relative.startswith("..") else f"./{relative}"


def restore_paths(text: str) -> str:
    """Undo `rewrite_paths`, one inverse per step and in the same order.

    A source file sits inside `~/.claude`, where `~` expands and a link
    resolves against that directory. `_absolute_link_target` maps `./x`,
    `x`, and `~/.claude/x` onto one target, so this picks the `./` form,
    which is the one the sources carry.
    """

    text = MARKDOWN_LINK.sub(lambda m: _relative_link_target(m.group(1)), text)
    return text.replace(f"{HOME_VAR}/", "~/")


# The one place the rulesets root is named, and the model whose bodies a job
# reads with none named. Every job reaches both through `Targets.rules_dir`,
# so moving the bodies is a change to the names below and to nothing inside
# any job.
RULESETS_DIRNAME = "rulesets"
DEFAULT_MODEL = "default"


def model_names(claude_home: Path, rulesets_dirname: str = RULESETS_DIRNAME) -> tuple[str, ...]:
    """Every model the rulesets root holds a directory for, sorted.

    A directory is what puts a model in play, so a job reaching every model
    finds them here and needs no list of its own.
    """

    root = claude_home / rulesets_dirname
    return tuple(sorted(child.name for child in root.iterdir() if child.is_dir()))


def agent_source(agents_dir: Path, name: str) -> Path:
    """The source file for one agent, or a ValueError naming what is there.

    A translation job scoped to one agent takes a name from the command line,
    and the source is what the name has to reach. The error carries the names
    that do resolve, so a misspelling is fixed from the message.
    """

    source = agents_dir / f"{name}.md"
    if not source.is_file():
        held = tuple(sorted(child.stem for child in agents_dir.glob("*.md")))
        raise ValueError(f"{name!r} names no agent source under {agents_dir}: {held}")
    return source


def all_rules(rules_dir: Path) -> list[Path]:
    """Every rule file, sorted by filename."""

    return sorted(rules_dir.glob("*.md"))


def unconditional_rules(rules_dir: Path) -> list[Path]:
    """The rule files that load every session, carrying no frontmatter.

    A rule carrying `paths:` frontmatter stays out. Claude Code loads one
    only once a matching file enters play, and each adapter reproduces that
    condition from the same frontmatter, so listing it here would put the
    text in every prompt and a second copy in a matching one.
    """

    return [
        rule
        for rule in all_rules(rules_dir)
        if parse_document(rule.read_text(encoding="utf-8")).frontmatter is None
    ]


def ordered_rules(rules_dir: Path, order: tuple[str, ...]) -> list[Path]:
    """The unconditional rules in the given order.

    Raises ValueError naming every stem the order and the directory disagree
    on, so a new rule lands in the order before a run silently drops it.
    """

    present = {rule.stem: rule for rule in unconditional_rules(rules_dir)}
    unlisted = sorted(set(present) - set(order))
    absent = [stem for stem in order if stem not in present]
    if unlisted or absent:
        raise ValueError(
            f"working rules order disagrees with {rules_dir}: unlisted {unlisted}, absent {absent}"
        )
    return [present[stem] for stem in order]


def home_relative(path: Path) -> str:
    """`~/`-prefixed where the path sits under the home directory, absolute otherwise."""

    return f"~/{path.relative_to(HOME)}" if path.is_relative_to(HOME) else str(path)


def uncommitted(repo: Path, paths: list[Path]) -> list[str]:
    """Whichever of `paths` git reports as changed in `repo`.

    A directory outside any git repository reports none, so a run still
    works where nobody versions the configuration.
    """

    if not paths:
        return []
    finished = subprocess.run(
        ["git", "-C", str(repo), "status", "--porcelain", "--", *(str(path) for path in paths)],
        capture_output=True,
        text=True,
        check=False,
    )
    if finished.returncode != 0:
        return []

    changed = []
    for line in finished.stdout.splitlines():
        # Porcelain v1 gives two status characters, a space, then the path,
        # and a rename gives "old -> new", where the new name is the target.
        named = line[3:]
        _, _, renamed = named.partition(" -> ")
        changed.append(renamed or named)
    return changed


def refuse_uncommitted(repo: Path, paths: list[Path]) -> None:
    """Stop a run that would write over changes nobody has committed.

    Each direction overwrites the side it writes to whole, so a target
    carrying an edit git has never seen loses that edit with no diff to
    recover it from.
    """

    changed = uncommitted(repo, paths)
    if changed:
        raise ValueError(
            "these carry uncommitted changes this run would overwrite: "
            + ", ".join(changed)
            + ". Commit them and run again."
        )


# The working-rules renderer owns this order conceptually, but `Targets`
# needs a default value for it, and the library every job imports cannot
# import a job without a cycle. Defining it here, once, and having the
# renderer carry the same name by importing it back keeps that one avenue
# open without a second copy of the tuple to drift from the first.
WORKING_RULES_ORDER = (
    "core-rules",
    "reasoning-guidelines",
    "inquiring",
    "ask-user-before-assuming",
    "asking-questions",
    "scope-is-user-decision",
    "claims",
    "epistemic-marks",
    "writing-prose",
    "writing-comments",
    "unasked-asides",
    "writing-code",
    "data-modeling",
    "repairing",
    "debugging",
    "search-tools",
    "reading-docs",
    "structural-search",
    "never-use-sed",
    "shell-quoting",
    "waiting-on-processes",
    "git-commit",
    "worktrees",
    "agent-delegation",
    "writing-plans",
    "scratchpad",
    "persistent-memory",
)


@dataclasses.dataclass(frozen=True)
class AgentDefinition:
    """One Claude Code agent definition, read from `agents/<name>.md`.

    `model` is None where the source names none, which means the agent
    inherits its caller's model. `tools` is None where the source names
    none, which grants every tool rather than no tool.
    """

    name: str
    description: str
    model: str | None
    tools: tuple[str, ...] | None
    body: str


@dataclasses.dataclass(frozen=True)
class Translation:
    """A generated agent file, with the source tool names it could not carry."""

    content: str
    dropped: tuple[str, ...]


def read_agent(path: Path) -> AgentDefinition:
    document = parse_document(path.read_text(encoding="utf-8"))
    frontmatter = document.frontmatter or {}
    tools = frontmatter.get("tools")
    return AgentDefinition(
        name=frontmatter["name"],
        description=frontmatter["description"],
        model=frontmatter.get("model"),
        tools=None if tools is None else tuple(t.strip() for t in tools.split(",") if t.strip()),
        body=document.body,
    )


def _map_tools(
    tools: tuple[str, ...] | None, names: dict[str, str]
) -> tuple[list[str] | None, tuple[str, ...]]:
    if tools is None:
        return None, ()
    mapped = [names[tool] for tool in tools if tool in names]
    dropped = tuple(tool for tool in tools if tool not in names)
    return mapped, dropped


def _render(frontmatter: dict, body: str) -> str:
    rendered = yaml.safe_dump(
        frontmatter,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=10**9,
    )
    return f"---\n{rendered}---\n\n{body}"


@dataclasses.dataclass(frozen=True)
class Targets:
    """The three roots this script reads from and writes to."""

    claude_home: Path
    pi_home: Path
    opencode_home: Path
    working_rules_order: tuple[str, ...] = WORKING_RULES_ORDER
    rulesets_dirname: str = RULESETS_DIRNAME
    model: str = DEFAULT_MODEL

    @property
    def claude_md(self) -> Path:
        return self.claude_home / "CLAUDE.md"

    @property
    def working_rules(self) -> Path:
        return self.claude_home / "references" / self.model / "working-rules.md"

    @property
    def rules_dir(self) -> Path:
        return self.claude_home / self.rulesets_dirname / self.model

    def for_model(self, model: str) -> Targets:
        """The same roots, reading and writing one other model's files.

        The rules directory and the reference file both carry the model's
        name, so they move together and neither can name a model the other
        does not.
        """

        return dataclasses.replace(self, model=model)

    @property
    def agents_dir(self) -> Path:
        return self.claude_home / "agents"

    @property
    def installed_plugins(self) -> Path:
        return self.claude_home / "plugins" / "installed_plugins.json"

    @property
    def settings(self) -> Path:
        return self.claude_home / "settings.json"

    @property
    def skill_paths_file(self) -> Path:
        return self.claude_home / "scratchpad" / "main" / "generated-skill-paths.json"

    @property
    def opencode_config(self) -> Path:
        return self.opencode_home / "opencode.json"


DEFAULT_TARGETS = Targets(
    claude_home=SCRIPT_ROOT,
    pi_home=HOME / ".pi" / "agent",
    opencode_home=HOME / ".config" / "opencode",
)


@dataclasses.dataclass(frozen=True)
class GeneratedFile:
    path: Path
    content: str


@dataclasses.dataclass(frozen=True)
class GeneratedKey:
    """One top-level key this script owns inside a hand-written JSON file.

    `after` names the key the new one follows when the file carries none
    yet, so a first write lands where a reader expects it rather than at the
    end. Every other key, and the file's key order, survives the write.
    """

    path: Path
    key: str
    value: object
    after: str


@dataclasses.dataclass(frozen=True)
class Plan:
    """Every file a run would write, and every tool grant that could not cross.

    `dropped` holds (target, agent, tool) for each source tool name the
    target has no equivalent for, so a run reports where an agent's reach
    narrowed rather than narrowing it silently.
    """

    files: tuple[GeneratedFile, ...]
    keys: tuple[GeneratedKey, ...]
    dropped: tuple[tuple[str, str, str], ...]


def _reorder(data: dict, key: str, value: object, after: str) -> dict:
    """`data` with `key` set to `value`, placed after `after` when new."""

    if key in data:
        return {name: (value if name == key else held) for name, held in data.items()}
    reordered: dict = {}
    for name, held in data.items():
        reordered[name] = held
        if name == after:
            reordered[key] = value
    if key not in reordered:
        reordered[key] = value
    return reordered


def _current(path: Path) -> str | None:
    return path.read_text(encoding="utf-8") if path.is_file() else None


def apply_plan(plan: Plan, *, check: bool) -> int:
    stale = 0
    for generated in plan.files:
        current = _current(generated.path)
        if current == generated.content:
            continue
        stale += 1
        if check:
            state = "missing" if current is None else "stale"
            print(f"{state}: {generated.path}")
            continue
        generated.path.parent.mkdir(parents=True, exist_ok=True)
        generated.path.write_text(generated.content, encoding="utf-8")
        if current is None:
            print(f"created: {generated.path} ({len(generated.content.encode())} bytes)")
        else:
            print(
                f"updated: {generated.path} "
                f"({len(current.encode())} -> {len(generated.content.encode())} bytes)"
            )

    for owned in plan.keys:
        # A config file absent altogether gets created holding this key
        # alone, so a fresh machine needs no hand-written stub first.
        data = json.loads(owned.path.read_text(encoding="utf-8")) if owned.path.is_file() else {}
        if data.get(owned.key) == owned.value:
            continue
        stale += 1
        if check:
            state = "missing" if owned.key not in data else "stale"
            print(f"{state}: {owned.key} in {owned.path}")
            continue
        rewritten = _reorder(data, owned.key, owned.value, owned.after)
        owned.path.parent.mkdir(parents=True, exist_ok=True)
        owned.path.write_text(json.dumps(rewritten, indent=2) + "\n", encoding="utf-8")
        print(f"updated: {owned.key} in {owned.path}")

    for label, agent, tool in plan.dropped:
        print(f"dropped: {tool} from {agent} for {label}, which carries no equivalent")

    total = len(plan.files) + len(plan.keys)
    if check:
        print(f"{stale} of {total} generated outputs out of date")
        return 1 if stale else 0
    print(f"{stale} of {total} generated outputs written")
    return 0
