#!/usr/bin/env python3
"""Tests for the agent-config generator under `scripts/sync-agent-configs.py`.

Run with `python3.14 -m pytest scripts/tests/test_sync_agent_configs.py`.

Every test builds its own source tree under a tmp_path and passes a Targets
naming it, so no test writes outside that directory. `DEFAULT_TARGETS` names
this checkout, so a test calling the generator without its own Targets would
write over the very files under test.

Two tests read outside tmp_path and write nothing there: the pair on
`DEFAULT_TARGETS`, and the round trip that renders this repository's own
`references/working-rules.md` back to itself.
"""

import dataclasses
import importlib.util
import json
import pathlib
import re
import subprocess
import sys

import pytest

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
SCRIPT_PATH = REPO_ROOT / "scripts" / "sync-agent-configs.py"

_spec = importlib.util.spec_from_file_location("sync_agent_configs", SCRIPT_PATH)
assert _spec is not None and _spec.loader is not None
sync = importlib.util.module_from_spec(_spec)
sys.modules["sync_agent_configs"] = sync
_spec.loader.exec_module(sync)

HOME = pathlib.Path.home()


class TestParseDocument:
    def test_frontmatter_block_separates_from_body(self):
        text = "---\nname: scout\nmodel: haiku\n---\n\nScout {\n  budget: 40\n}\n"

        doc = sync.parse_document(text)

        assert doc.frontmatter == {"name": "scout", "model": "haiku"}, (
            "a leading --- block must parse as YAML frontmatter"
        )
        assert doc.body == "Scout {\n  budget: 40\n}\n", (
            "the body must be the text after the closing ---, with the blank separator dropped"
        )

    def test_file_without_frontmatter_reports_none(self):
        text = "CoreRules {\n  AppliesWhen { every context }\n}\n"

        doc = sync.parse_document(text)

        assert doc.frontmatter is None, (
            "a file opening on something other than --- carries no frontmatter"
        )
        assert doc.body == text, "the whole text is the body when no frontmatter opens the file"

    def test_horizontal_rule_mid_file_is_not_frontmatter(self):
        text = "Some prose\n\n---\n\nmore prose\n"

        doc = sync.parse_document(text)

        assert doc.frontmatter is None, (
            "a --- that is not the first line opens no frontmatter block"
        )


class TestRewritePaths:
    def test_tilde_prefix_becomes_the_home_variable(self):
        rewritten = sync.rewrite_paths("read `~/.claude/references/bash-style-guide.md` in full")

        assert rewritten == "read `$HOME/.claude/references/bash-style-guide.md` in full", (
            "a ~/ prefix must resolve, since the generated file sits where ~ is not expanded"
        )

    def test_no_output_names_the_running_user(self):
        rewritten = sync.rewrite_paths("`~/.claude/x` and [y](./rules/y.md) and `../.dotfiles/z`")

        assert str(HOME) not in rewritten, (
            "the active home directory must reach no generated byte, since a name baked "
            "into a committed file breaks on every other machine"
        )

    def test_bare_tilde_survives(self):
        text = "<hello>\n~\nHi!\n/~\n</hello>\n"

        assert sync.rewrite_paths(text) == text, (
            "a ~ that starts no path is decoration and must survive byte for byte"
        )

    def test_relative_link_target_resolves_against_the_home_variable(self):
        rewritten = sync.rewrite_paths("live in [core-rules.md](./rules/core-rules.md) and load")

        assert rewritten == (
            "live in [core-rules.md]($HOME/.claude/rules/core-rules.md) and load"
        ), "a link relative to ~/.claude does not resolve from the directory the output sits in"

    def test_parent_relative_link_target_resolves(self):
        rewritten = sync.rewrite_paths("see [x](../.dotfiles/git/ignore)")

        assert rewritten == "see [x]($HOME/.dotfiles/git/ignore)", (
            "a ../ segment must collapse rather than survive into the resolved path"
        )

    def test_home_variable_link_survives(self):
        text = "at [x]($HOME/.claude/rules/core-rules.md)"

        assert sync.rewrite_paths(text) == text, (
            "a target already naming $HOME must not resolve a second time against ~/.claude"
        )

    def test_url_link_survives(self):
        text = "per [Peirce](https://plato.stanford.edu/entries/peirce/)"

        assert sync.rewrite_paths(text) == text, "an http(s) target names no file on disk"

    def test_anchor_link_survives(self):
        text = "see [above](#precedence)"

        assert sync.rewrite_paths(text) == text, "a fragment target names no file on disk"

    def test_absolute_link_survives(self):
        text = f"at [x]({HOME}/.claude/rules/core-rules.md)"

        assert sync.rewrite_paths(text) == text, "an already-absolute target needs no rewrite"

    def test_prose_around_a_rewrite_survives_byte_for_byte(self):
        text = "Alpha `~/.claude/x` beta\n\n- gamma: delta\n  - epsilon\n"

        assert (
            sync.rewrite_paths(text)
            == "Alpha `$HOME/.claude/x` beta\n\n- gamma: delta\n  - epsilon\n"
        ), "only the path token changes; every other byte, newline and indent included, survives"


class TestRestorePaths:
    def test_home_variable_becomes_a_tilde_prefix(self):
        restored = sync.restore_paths("read `$HOME/.claude/references/bash-style-guide.md` in full")

        assert restored == "read `~/.claude/references/bash-style-guide.md` in full", (
            "a source file sits where ~ expands, so the variable the render carries goes back"
        )

    def test_link_target_inside_claude_home_becomes_dot_relative(self):
        restored = sync.restore_paths("live in [core-rules.md]($HOME/.claude/rules/core-rules.md)")

        assert restored == "live in [core-rules.md](./rules/core-rules.md)", (
            "a source names a sibling under ~/.claude by the ./ form the forward run resolves"
        )

    def test_link_target_outside_claude_home_becomes_parent_relative(self):
        restored = sync.restore_paths("see [x]($HOME/.dotfiles/git/ignore)")

        assert restored == "see [x](../.dotfiles/git/ignore)", (
            "a target under the home directory but outside ~/.claude climbs one level"
        )

    def test_url_link_survives(self):
        text = "per [Peirce](https://plato.stanford.edu/entries/peirce/)"

        assert sync.restore_paths(text) == text, "an http(s) target names no file on disk"

    def test_anchor_link_survives(self):
        text = "see [above](#precedence)"

        assert sync.restore_paths(text) == text, "a fragment target names no file on disk"

    def test_absolute_link_outside_the_home_directory_survives(self):
        text = "at [x](/etc/hosts)"

        assert sync.restore_paths(text) == text, (
            "a path outside the home directory has no relative form under ~/.claude"
        )

    def test_bare_tilde_and_dollar_survive(self):
        text = "<hello>\n~\nHi!\n/~\n</hello>\n\n`$dir/$slug__$DD-MM-YY-HHmm.md`\n"

        assert sync.restore_paths(text) == text, (
            "a ~ that starts no path and a $ that opens no HOME are text, not paths"
        )

    def test_restore_inverts_rewrite(self):
        source = (
            "<hello>\n~\n/~\n</hello>\n\n"
            "The rules live in [core-rules.md](./rules/core-rules.md) and load.\n\n"
            "The ignore at `~/.dotfiles/git/ignore` covers it, per [x](../.dotfiles/git/ignore).\n\n"
            "Read `~/.claude/references/bash-style-guide.md`, per "
            "[Peirce](https://plato.stanford.edu/entries/peirce/) and [above](#precedence).\n"
        )

        assert sync.restore_paths(sync.rewrite_paths(source)) == source, (
            "a render that does not restore to its own sources drifts a little on every sync"
        )


def _write(path: pathlib.Path, text: str) -> pathlib.Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


PREAMBLE = '<hello from="user">\n~\n/~\n</hello>\n\n<stance>\n\nPlay, per [x](./rules/alpha.md).\n\n</stance>'

FENCED_RULE_TAG = '```xml\n<rule name="a-template-not-a-boundary">\n</rule>\n```'


def _element(name: str, body: str) -> str:
    """One `<rule>` element, the unit a rules file and a render section share."""

    return f'<rule name="{name}">\n\n{body}\n\n</rule>'


def _reference(preamble: str, *sections: str, title: str = "# Working Rules") -> str:
    """A render assembled from a preamble and whatever sections follow."""

    return "\n\n".join([title, preamble, *sections]) + "\n"


class TestBuildAgentsMarkdown:
    def _tree(self, tmp_path: pathlib.Path) -> tuple[pathlib.Path, pathlib.Path]:
        claude_md = _write(tmp_path / "CLAUDE.md", "# Preamble\n\nStance goes here.\n")
        rules = tmp_path / "rules"
        _write(rules / "alpha.md", "Alpha {\n  always\n}\n")
        _write(
            rules / "gated.md",
            '---\npaths:\n  - "**/*.sh"\n---\n\nGated {\n  sometimes\n}\n',
        )
        _write(rules / "zeta.md", "Zeta {\n  always\n}\n")
        return claude_md, rules

    def test_rule_carrying_paths_frontmatter_stays_out(self, tmp_path):
        claude_md, rules = self._tree(tmp_path)

        built = sync.build_agents_markdown(claude_md, rules)

        assert "Gated {" not in built, (
            "the extension appends a path-scoped rule when a matching file is in play, so "
            "carrying it here would load it in every session and twice in a matching one"
        )
        assert "paths:" not in built, "no frontmatter reaches the context file"

    def test_rule_without_frontmatter_goes_in(self, tmp_path):
        claude_md, rules = self._tree(tmp_path)

        built = sync.build_agents_markdown(claude_md, rules)

        assert "Alpha {\n  always\n}" in built, "a rule with no frontmatter loads every session"
        assert "Zeta {\n  always\n}" in built, "a rule with no frontmatter loads every session"

    def test_preamble_leads_and_rules_follow_in_filename_order(self, tmp_path):
        claude_md, rules = self._tree(tmp_path)

        built = sync.build_agents_markdown(claude_md, rules)

        assert built.index("# Preamble") < built.index("Alpha {") < built.index("Zeta {"), (
            "CLAUDE.md leads and rules follow sorted by filename, so the output is deterministic"
        )

    def test_frontmatter_delimiters_do_not_reach_the_output(self, tmp_path):
        claude_md, rules = self._tree(tmp_path)

        built = sync.build_agents_markdown(claude_md, rules)

        assert "paths:" not in built, "an excluded rule contributes none of its frontmatter either"

    def test_paths_in_rule_bodies_are_rewritten(self, tmp_path):
        claude_md = _write(tmp_path / "CLAUDE.md", "# Preamble\n")
        rules = tmp_path / "rules"
        _write(rules / "alpha.md", "Alpha {\n  read `~/.claude/references/x.md`\n}\n")

        built = sync.build_agents_markdown(claude_md, rules)

        assert "`$HOME/.claude/references/x.md`" in built, (
            "a rule body reaches the generated file through the same path rewrite as the preamble"
        )

    def test_sections_are_separated_by_one_blank_line(self, tmp_path):
        claude_md = _write(tmp_path / "CLAUDE.md", "# Preamble\n\n\n")
        rules = tmp_path / "rules"
        _write(rules / "alpha.md", "Alpha {\n}\n\n\n")
        _write(rules / "zeta.md", "Zeta {\n}\n")

        built = sync.build_agents_markdown(claude_md, rules)

        assert built == "# Preamble\n\nAlpha {\n}\n\nZeta {\n}\n", (
            "trailing blank lines in a source must not vary the joint, or the output stops "
            "being a function of the rule text alone"
        )


ALPHA = _element("alpha", "Alpha holds.")
ZETA = _element("zeta", f"Zeta holds.\n\n{FENCED_RULE_TAG}")


class TestBuildWorkingRules:
    def _tree(self, tmp_path: pathlib.Path) -> tuple[pathlib.Path, pathlib.Path]:
        claude_md = _write(tmp_path / "CLAUDE.md", f"{PREAMBLE}\n")
        rules = tmp_path / "rules"
        _write(rules / "alpha.md", f"{ALPHA}\n")
        _write(
            rules / "gated.md", f'---\npaths:\n  - "**/*.sh"\n---\n\n{_element("gated", "G.")}\n'
        )
        _write(rules / "zeta.md", f"{ZETA}\n")
        return claude_md, rules

    def test_render_opens_on_its_title_then_the_preamble(self, tmp_path):
        claude_md, rules = self._tree(tmp_path)

        built = sync.build_working_rules(claude_md, rules, ("alpha", "zeta"))

        assert built.split("\n")[0] == sync.TITLE, "the render owns the one h1 and opens on it"
        assert built.index("<hello") < built.index('<rule name="alpha">'), (
            "CLAUDE.md is the preamble, so it sits between the title and the first rule"
        )

    def test_each_rules_file_reaches_the_render_whole(self, tmp_path):
        claude_md, rules = self._tree(tmp_path)

        built = sync.build_working_rules(claude_md, rules, ("alpha", "zeta"))

        assert sync.parse_reference(built).rules == (
            sync.RuleSection("alpha", ALPHA),
            sync.RuleSection("zeta", ZETA),
        ), "a section of the render is the rules file that produced it, wrapper included"

    def test_rules_follow_the_given_order(self, tmp_path):
        claude_md, rules = self._tree(tmp_path)

        built = sync.build_working_rules(claude_md, rules, ("zeta", "alpha"))

        assert [section.name for section in sync.parse_reference(built).rules] == [
            "zeta",
            "alpha",
        ], "the render reads as one document, so the caller orders it by topic, not by filename"

    def test_path_scoped_rule_stays_out(self, tmp_path):
        claude_md, rules = self._tree(tmp_path)

        built = sync.build_working_rules(claude_md, rules, ("alpha", "zeta"))

        assert "gated" not in built, "the render carries the rules that load every session"

    def test_sections_join_on_one_blank_line_and_the_file_ends_on_one_newline(self, tmp_path):
        unlinked = '<hello from="user">\n~\n/~\n</hello>'
        claude_md = _write(tmp_path / "CLAUDE.md", f"{unlinked}\n\n\n")
        rules = tmp_path / "rules"
        _write(rules / "alpha.md", f"{ALPHA}\n\n\n")
        _write(rules / "zeta.md", f"{ZETA}\n")

        built = sync.build_working_rules(claude_md, rules, ("alpha", "zeta"))

        assert built == _reference(unlinked, ALPHA, ZETA), (
            "trailing blank lines in a source must not vary the joint, or the render stops "
            "being a function of the source text alone"
        )

    def test_relative_link_in_the_preamble_resolves(self, tmp_path):
        claude_md, rules = self._tree(tmp_path)

        built = sync.build_working_rules(claude_md, rules, ("alpha", "zeta"))

        assert "[x]($HOME/.claude/rules/alpha.md)" in built, (
            "the render sits under references/, where a link relative to ~/.claude breaks"
        )

    def test_order_naming_no_file_reports_the_stem(self, tmp_path):
        claude_md, rules = self._tree(tmp_path)

        with pytest.raises(ValueError, match="ghost"):
            sync.build_working_rules(claude_md, rules, ("alpha", "zeta", "ghost"))

    def test_unconditional_rule_missing_from_the_order_reports_the_stem(self, tmp_path):
        claude_md, rules = self._tree(tmp_path)

        with pytest.raises(ValueError, match="zeta"):
            sync.build_working_rules(claude_md, rules, ("alpha",))

    def test_a_rules_file_carrying_no_rule_element_reports_its_path(self, tmp_path):
        claude_md, rules = self._tree(tmp_path)
        _write(rules / "alpha.md", "# Alpha\n\nThis applies always.\n")

        with pytest.raises(ValueError, match=re.escape("alpha.md")):
            sync.build_working_rules(claude_md, rules, ("alpha", "zeta"))

    def test_a_name_attribute_disagreeing_with_the_stem_reports_both(self, tmp_path):
        claude_md, rules = self._tree(tmp_path)
        _write(rules / "alpha.md", f"{_element('alfa', 'Alpha holds.')}\n")

        with pytest.raises(ValueError, match="alfa"):
            sync.build_working_rules(claude_md, rules, ("alpha", "zeta"))

    def test_a_claude_md_carrying_no_preamble_tag_reports_its_path(self, tmp_path):
        claude_md, rules = self._tree(tmp_path)
        _write(claude_md, "# Stance\n\nWork here proceeds as play.\n")

        with pytest.raises(ValueError, match=re.escape("CLAUDE.md")):
            sync.build_working_rules(claude_md, rules, ("alpha", "zeta"))


class TestParseReference:
    def test_the_preamble_runs_from_the_title_to_the_first_rule(self):
        parsed = sync.parse_reference(_reference(PREAMBLE, _element("alpha", "Alpha holds.")))

        assert parsed.preamble == PREAMBLE, (
            "CLAUDE.md is what sits between the title and the first rule, and the title is not it"
        )

    def test_a_section_comes_back_as_the_element_it_was_built_from(self):
        alpha = _element("alpha", "Alpha holds.")

        parsed = sync.parse_reference(_reference(PREAMBLE, alpha, _element("zeta", "Zeta holds.")))

        assert [section.name for section in parsed.rules] == ["alpha", "zeta"], (
            "a rule is named by the attribute on its wrapper, which is the file stem"
        )
        assert parsed.rules[0].text == alpha, (
            "the section carries its wrapper, so the rules file it lands in is the section itself"
        )

    def test_a_rule_tag_inside_a_fence_opens_no_section(self):
        zeta = _element("zeta", FENCED_RULE_TAG)

        parsed = sync.parse_reference(_reference(PREAMBLE, _element("alpha", "A."), zeta))

        assert [section.name for section in parsed.rules] == ["alpha", "zeta"], (
            "a fenced block is a template a model copies, and a tag inside it is text"
        )
        assert parsed.rules[1].text == zeta, "the fenced tag stays inside the rule carrying it"

    def test_a_document_not_opening_on_the_title_raises(self):
        document = _reference(PREAMBLE, _element("alpha", "A."), title="# Rules")

        with pytest.raises(ValueError, match=re.escape(sync.TITLE)):
            sync.parse_reference(document)

    def test_a_rule_that_never_closes_raises_naming_it(self):
        with pytest.raises(ValueError, match="alpha"):
            sync.parse_reference(_reference(PREAMBLE, '<rule name="alpha">\n\nAlpha holds.'))

    def test_a_document_with_no_preamble_raises(self):
        with pytest.raises(ValueError):
            sync.parse_reference(_reference("", _element("alpha", "A.")))

    def test_content_outside_every_rule_raises_quoting_it(self):
        document = _reference(PREAMBLE, _element("alpha", "A."), "A loose sentence.")

        with pytest.raises(ValueError, match="A loose sentence"):
            sync.parse_reference(document)


AGENT_BODY = "Scout {\n  Options {\n    budget: 1..200 = 40\n  }\n}\n"


def _agent_source(tmp_path: pathlib.Path, name: str, **keys: str) -> pathlib.Path:
    lines = [f"name: {name}", "description: Use this agent to scout, and to report."]
    lines += [f"{key}: {value}" for key, value in keys.items()]
    frontmatter = "\n".join(lines)
    return _write(tmp_path / f"{name}.md", f"---\n{frontmatter}\n---\n\n{AGENT_BODY}")


class TestReadAgent:
    def test_absent_tools_key_reads_as_every_tool(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "orchestrator"))

        assert agent.tools is None, (
            "a source naming no tools grants every tool, which differs from granting none"
        )

    def test_comma_separated_tools_split_into_names(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "scout", tools="Read, Grep, Glob"))

        assert agent.tools == ("Read", "Grep", "Glob"), (
            "the source writes tools as one comma-separated string"
        )

    def test_absent_model_reads_as_none(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "orchestrator"))

        assert agent.model is None, "a source naming no model inherits the caller's model"


class TestTranslateForOpencode:
    def test_model_tier_becomes_a_provider_id(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "scout", model="haiku"))

        translated = sync.translate_for_opencode(agent)

        assert "model: anthropic/claude-haiku-4-5" in translated.content, (
            "opencode names a model by provider/model id, not by Claude's tier name"
        )

    def test_absent_model_emits_no_model_key(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "orchestrator"))

        translated = sync.translate_for_opencode(agent)

        assert "model:" not in translated.content, (
            "emitting a model key where the source names none would pin an agent "
            "that should inherit"
        )

    def test_tools_become_a_lowercase_map_to_true(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "scout", tools="Read, Grep, Glob, Bash"))

        translated = sync.translate_for_opencode(agent)
        frontmatter = sync.parse_document(translated.content).frontmatter

        assert frontmatter["tools"] == {
            "read": True,
            "grep": True,
            "glob": True,
            "bash": True,
        }, "opencode reads tools as a map of its own lowercase tool names to booleans"

    def test_agent_tool_maps_to_task(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "skill-designer", tools="Read, Agent"))

        translated = sync.translate_for_opencode(agent)
        frontmatter = sync.parse_document(translated.content).frontmatter

        assert frontmatter["tools"] == {"read": True, "task": True}, (
            "opencode spawns subagents through `task`, which is what Claude's Agent names"
        )

    def test_claude_only_tools_drop_and_are_reported(self, tmp_path):
        agent = sync.read_agent(
            _agent_source(tmp_path, "spider", tools="Bash, ToolSearch, mcp__linkup__linkup-search")
        )

        translated = sync.translate_for_opencode(agent)
        frontmatter = sync.parse_document(translated.content).frontmatter

        assert frontmatter["tools"] == {"bash": True}, (
            "a tool opencode does not carry must not reach its frontmatter under any name"
        )
        assert translated.dropped == ("ToolSearch", "mcp__linkup__linkup-search"), (
            "a dropped tool narrows the agent's reach, so the run must name what it dropped"
        )

    def test_absent_tools_emits_no_tools_key(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "orchestrator"))

        translated = sync.translate_for_opencode(agent)

        assert "tools:" not in translated.content, (
            "an empty tools map would grant no tools, where the source granted every tool"
        )

    def test_mode_is_subagent(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "scout"))

        translated = sync.translate_for_opencode(agent)

        assert sync.parse_document(translated.content).frontmatter["mode"] == "subagent", (
            "these definitions are spawned by another agent, never run as the session agent"
        )

    def test_description_survives_verbatim(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "scout"))

        translated = sync.translate_for_opencode(agent)

        assert (
            sync.parse_document(translated.content).frontmatter["description"]
            == "Use this agent to scout, and to report."
        ), "the description is what a router matches on, so it must carry across unchanged"

    def test_body_becomes_the_system_prompt_unchanged(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "scout", model="haiku"))

        translated = sync.translate_for_opencode(agent)

        assert sync.parse_document(translated.content).body == AGENT_BODY, (
            "the body is the system prompt and no rewrite applies to it"
        )


class TestResolveSkillPaths:
    def _tree(self, tmp_path, enabled: dict, plugins: dict) -> tuple[pathlib.Path, pathlib.Path]:
        installed = _write(
            tmp_path / "installed_plugins.json",
            json.dumps({"version": 2, "plugins": plugins}),
        )
        settings = _write(tmp_path / "settings.json", json.dumps({"enabledPlugins": enabled}))
        return installed, settings

    def test_enabled_plugin_with_skills_contributes_its_path(self, tmp_path):
        install = tmp_path / "cache" / "seed" / "software"
        (install / "skills").mkdir(parents=True)
        installed, settings = self._tree(
            tmp_path,
            {"software@seed": True},
            {"software@seed": [{"scope": "user", "installPath": str(install)}]},
        )

        assert sync.resolve_skill_paths(installed, settings) == [str(install / "skills")], (
            "an enabled plugin's skills directory is what the other agents need on their path"
        )

    def test_enabled_plugin_without_skills_contributes_nothing(self, tmp_path):
        install = tmp_path / "cache" / "official" / "typescript-lsp"
        install.mkdir(parents=True)
        installed, settings = self._tree(
            tmp_path,
            {"typescript-lsp@official": True},
            {"typescript-lsp@official": [{"scope": "user", "installPath": str(install)}]},
        )

        assert sync.resolve_skill_paths(installed, settings) == [], (
            "a plugin carrying hooks or MCP servers alone has no skills directory to add"
        )

    def test_disabled_plugin_contributes_nothing(self, tmp_path):
        install = tmp_path / "cache" / "seed" / "switchboard"
        (install / "skills").mkdir(parents=True)
        installed, settings = self._tree(
            tmp_path,
            {"switchboard@seed": False},
            {"switchboard@seed": [{"scope": "user", "installPath": str(install)}]},
        )

        assert sync.resolve_skill_paths(installed, settings) == [], (
            "a disabled plugin's skills stay out, or the other agents load what Claude does not"
        )

    def test_enabled_plugin_missing_from_the_install_record_is_skipped(self, tmp_path):
        installed, settings = self._tree(tmp_path, {"ghost@nowhere": True}, {})

        assert sync.resolve_skill_paths(installed, settings) == [], (
            "an enable naming no installed plugin resolves to no path rather than raising"
        )

    def test_user_scope_wins_over_project_scope(self, tmp_path):
        old = tmp_path / "cache" / "skill-creator" / "1.0.0"
        new = tmp_path / "cache" / "skill-creator" / "2.0.0"
        (old / "skills").mkdir(parents=True)
        (new / "skills").mkdir(parents=True)
        installed, settings = self._tree(
            tmp_path,
            {"skill-creator@official": True},
            {
                "skill-creator@official": [
                    {"scope": "project", "installPath": str(old)},
                    {"scope": "user", "installPath": str(new)},
                ]
            },
        )

        assert sync.resolve_skill_paths(installed, settings) == [str(new / "skills")], (
            "two installed versions of one plugin would put two copies of each skill on the "
            "path, and the user-scoped record is the one a user-level enable turns on"
        )

    def test_project_scope_serves_when_no_user_record_exists(self, tmp_path):
        install = tmp_path / "cache" / "seed" / "visualizer"
        (install / "skills").mkdir(parents=True)
        installed, settings = self._tree(
            tmp_path,
            {"visualizer@seed": True},
            {"visualizer@seed": [{"scope": "project", "installPath": str(install)}]},
        )

        assert sync.resolve_skill_paths(installed, settings) == [str(install / "skills")], (
            "a plugin installed only against a project still resolves to one install path"
        )

    def test_paths_come_back_sorted(self, tmp_path):
        for name in ("zeta", "alpha"):
            (tmp_path / "cache" / name / "skills").mkdir(parents=True)
        installed, settings = self._tree(
            tmp_path,
            {"zeta@seed": True, "alpha@seed": True},
            {
                "zeta@seed": [{"scope": "user", "installPath": str(tmp_path / "cache" / "zeta")}],
                "alpha@seed": [{"scope": "user", "installPath": str(tmp_path / "cache" / "alpha")}],
            },
        )

        resolved = sync.resolve_skill_paths(installed, settings)

        assert resolved == sorted(resolved), (
            "the order must not follow the JSON key order, or the output churns between runs"
        )


class TestTranslateForPi:
    def test_model_stays_a_bare_tier_name(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "scout", model="haiku"))

        translated = sync.translate_for_pi(agent)

        assert sync.parse_document(translated.content).frontmatter["model"] == "haiku", (
            "pi resolves a tier name through its own model catalog"
        )

    def test_absent_model_emits_no_model_key(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "orchestrator"))

        translated = sync.translate_for_pi(agent)

        assert "model:" not in translated.content, (
            "emitting a model key where the source names none would pin an agent "
            "that should inherit"
        )

    def test_tools_render_comma_separated(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "scout", tools="Read, Grep, Bash"))

        translated = sync.translate_for_pi(agent)

        assert sync.parse_document(translated.content).frontmatter["tools"] == "read, grep, bash", (
            "pi reads tools as one comma-separated string, not as a map"
        )

    def test_glob_maps_to_find(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "scout", tools="Glob"))

        translated = sync.translate_for_pi(agent)

        assert sync.parse_document(translated.content).frontmatter["tools"] == "find", (
            "pi's find takes a glob pattern, which is what Claude's Glob does"
        )

    def test_tools_pi_lacks_drop_and_are_reported(self, tmp_path):
        agent = sync.read_agent(
            _agent_source(tmp_path, "skill-designer", tools="Read, Agent, ToolSearch")
        )

        translated = sync.translate_for_pi(agent)

        assert sync.parse_document(translated.content).frontmatter["tools"] == "read", (
            "pi carries bash, read, edit, write, grep, find, and ls, and nothing else"
        )
        assert translated.dropped == ("Agent", "ToolSearch"), (
            "a dropped tool narrows the agent's reach, so the run must name what it dropped"
        )

    def test_absent_tools_emits_no_tools_key(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "orchestrator"))

        translated = sync.translate_for_pi(agent)

        assert "tools:" not in translated.content, (
            "an empty tools list would grant no tools, where the source granted every tool"
        )

    def test_skills_are_inherited(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "scout"))

        translated = sync.translate_for_pi(agent)

        assert sync.parse_document(translated.content).frontmatter["inheritSkills"] is True, (
            "a subagent that cannot reach the skills its prompt names stalls on them"
        )

    def test_body_becomes_the_system_prompt_unchanged(self, tmp_path):
        agent = sync.read_agent(_agent_source(tmp_path, "scout", model="sonnet"))

        translated = sync.translate_for_pi(agent)

        assert sync.parse_document(translated.content).body == AGENT_BODY, (
            "the body is the system prompt and no rewrite applies to it"
        )


@pytest.fixture
def targets(tmp_path):
    """A complete source tree plus empty pi and opencode roots."""

    return _targets(tmp_path)


def _targets(tmp_path: pathlib.Path) -> object:
    claude_home = tmp_path / "claude"
    _write(claude_home / "CLAUDE.md", f"{PREAMBLE}\n")
    _write(claude_home / "rules" / "alpha.md", f"{ALPHA}\n")
    _write(
        claude_home / "rules" / "gated.md",
        f'---\npaths:\n  - "**/*.sh"\n---\n\n{_element("gated", "Gated holds.")}\n',
    )
    _agent_source(claude_home / "agents", "scout", model="haiku", tools="Read, Glob, Agent")
    _agent_source(claude_home / "agents", "orchestrator")

    plugin = tmp_path / "cache" / "software"
    (plugin / "skills").mkdir(parents=True)
    _write(
        claude_home / "plugins" / "installed_plugins.json",
        json.dumps({"plugins": {"software@seed": [{"scope": "user", "installPath": str(plugin)}]}}),
    )
    _write(claude_home / "settings.json", json.dumps({"enabledPlugins": {"software@seed": True}}))

    return sync.Targets(
        claude_home=claude_home,
        pi_home=tmp_path / "pi" / "agent",
        opencode_home=tmp_path / "config" / "opencode",
        working_rules_order=("alpha",),
    )


def _git(repo: pathlib.Path, *args: str) -> None:
    """Run one git command in `repo`, with the user's hooks and signing off."""

    subprocess.run(
        ["git", "-C", str(repo), "-c", "core.hooksPath=", "-c", "commit.gpgsign=false", *args],
        check=True,
        capture_output=True,
    )


@pytest.fixture
def committed(tmp_path):
    """The same source tree, plus its render, committed in a git repository."""

    aimed = _targets(tmp_path)
    _write(aimed.working_rules, _reference(RENDERED_PREAMBLE, ALPHA))
    _git(aimed.claude_home, "init", "-q")
    _git(aimed.claude_home, "config", "user.email", "test@example.invalid")
    _git(aimed.claude_home, "config", "user.name", "Test")
    _git(aimed.claude_home, "add", "-A")
    _git(aimed.claude_home, "commit", "-q", "-m", "the tree as the generator last left it")
    return aimed


class TestBuildPlan:
    def test_working_rules_render_lands_under_references(self, targets):
        plan = sync.build_plan(targets)
        by_path = {f.path: f.content for f in plan.files}
        written = by_path[targets.claude_home / "references" / "working-rules.md"]

        assert "<stance>" in written and ALPHA in written and "gated" not in written, (
            "the render carries the preamble and every always-on rule, and no path-scoped one"
        )

    def test_pi_agents_markdown_carries_the_preamble_and_the_unconditional_rules(self, targets):
        plan = sync.build_plan(targets)
        by_path = {f.path: f.content for f in plan.files}
        written = by_path[targets.pi_home / "AGENTS.md"]

        assert "<stance>" in written, "pi reads the CLAUDE.md preamble from its context file"
        assert ALPHA in written, (
            "pi offers no second mechanism for rule files, so the rules travel in its context file"
        )
        assert "gated" not in written, (
            "a path-scoped rule reaches pi through the extension when a matching file is in play, "
            "so carrying it here would load it in every session and twice in a matching one"
        )

    def test_opencode_agents_markdown_carries_the_preamble_alone(self, targets):
        plan = sync.build_plan(targets)
        by_path = {f.path: f.content for f in plan.files}
        written = by_path[targets.opencode_home / "AGENTS.md"]

        assert "<stance>" in written, "opencode reads the CLAUDE.md preamble from its context file"
        assert ALPHA not in written, (
            "opencode reads the rules through `instructions`, so repeating them here would double them"
        )

    def test_opencode_instructions_list_the_unconditional_rules(self, targets):
        plan = sync.build_plan(targets)
        owned = {(key.path, key.key): key.value for key in plan.keys}
        listed = owned[(targets.opencode_config, "instructions")]

        assert any(entry.endswith("alpha.md") for entry in listed), (
            "every rule that loads each session must reach opencode"
        )

    def test_opencode_instructions_exclude_a_path_scoped_rule(self, targets):
        plan = sync.build_plan(targets)
        owned = {(key.path, key.key): key.value for key in plan.keys}
        listed = owned[(targets.opencode_config, "instructions")]

        assert not any(entry.endswith("gated.md") for entry in listed), (
            "the plugin appends a path-scoped rule when a matching file is in play, so listing it "
            "here would load it in every session and twice in a matching one"
        )

    def test_build_plan_writes_no_copy_of_a_path_scoped_rule(self, targets):
        plan = sync.build_plan(targets)

        assert not any(f.path.name == "gated.md" for f in plan.files), (
            "the plugin reads a path-scoped rule from its canonical file and strips the "
            "frontmatter itself, so no copy exists to fall out of date"
        )

    def test_every_source_agent_yields_one_file_per_target(self, targets):
        plan = sync.build_plan(targets)
        paths = {f.path for f in plan.files}

        assert {
            targets.opencode_home / "agents" / "scout.md",
            targets.opencode_home / "agents" / "orchestrator.md",
            targets.pi_home / "agents" / "scout.md",
            targets.pi_home / "agents" / "orchestrator.md",
        } <= paths, "each source agent must reach both targets"

    def test_skill_paths_render_as_a_paths_object(self, targets):
        plan = sync.build_plan(targets)
        by_path = {f.path: f.content for f in plan.files}
        written = json.loads(by_path[targets.skill_paths_file])

        assert list(written) == ["paths"], (
            "the consumer merging these reads a single paths key and nothing else"
        )

    def test_dropped_tools_are_reported_per_agent_and_target(self, targets):
        plan = sync.build_plan(targets)

        assert plan.dropped == (("pi", "scout", "Agent"),), (
            "pi carries no subagent tool, so scout's Agent grant cannot cross and must be named; "
            "opencode's task covers it, so nothing drops there"
        )


RENDERED_PREAMBLE = PREAMBLE.replace("./rules/alpha.md", "$HOME/.claude/rules/alpha.md")


class TestBuildReversePlan:
    def _files(self, targets, *sections, order=None) -> dict:
        aimed = (
            targets if order is None else dataclasses.replace(targets, working_rules_order=order)
        )
        _write(aimed.working_rules, _reference(RENDERED_PREAMBLE, *sections))
        return {f.path: f.content for f in sync.build_reverse_plan(aimed).files}

    def test_each_rule_element_lands_in_its_own_rules_file(self, targets):
        files = self._files(targets, ALPHA)

        assert files[targets.rules_dir / "alpha.md"] == f"{ALPHA}\n", (
            "a rules file is the render's section for it, wrapper included and nothing above it"
        )

    def test_the_preamble_lands_in_claude_md_with_its_paths_restored(self, targets):
        files = self._files(targets, ALPHA)

        assert files[targets.claude_md] == f"{PREAMBLE}\n", (
            "CLAUDE.md sits inside ~/.claude, where the render's resolved link does not belong"
        )

    def test_the_reverse_touches_the_sources_and_nothing_else(self, targets):
        _write(targets.working_rules, _reference(RENDERED_PREAMBLE, ALPHA))

        plan = sync.build_reverse_plan(targets)

        assert {f.path for f in plan.files} == {
            targets.claude_md,
            targets.rules_dir / "alpha.md",
        }, "the reverse writes the sources, and a forward run projects them onto pi and opencode"
        assert plan.keys == () and plan.dropped == (), (
            "no generated key and no agent translation belongs to this direction"
        )

    def test_a_rule_element_whose_file_does_not_exist_yet_gets_one(self, targets):
        files = self._files(targets, ALPHA, ZETA, order=("alpha", "zeta"))

        assert files[targets.rules_dir / "zeta.md"] == f"{ZETA}\n", (
            "a rule added to the render creates its file, with its stem added to the order"
        )

    def test_a_rule_the_order_does_not_name_raises(self, targets):
        with pytest.raises(ValueError, match="ghost"):
            self._files(targets, ALPHA, _element("ghost", "Ghost holds."))

    def test_rules_out_of_the_order_sequence_raise(self, targets):
        with pytest.raises(ValueError, match="zeta"):
            self._files(targets, ZETA, ALPHA, order=("alpha", "zeta"))

    def test_a_rule_resolving_to_a_path_scoped_file_raises(self, targets):
        with pytest.raises(ValueError, match=re.escape("gated.md")):
            self._files(targets, ALPHA, _element("gated", "G."), order=("alpha", "gated"))


class TestApply:
    def test_first_run_creates_missing_parent_directories(self, targets):
        assert not targets.pi_home.exists(), "the fixture starts with no pi root"

        sync.main([], targets=targets)

        assert (targets.pi_home / "agents" / "scout.md").is_file(), (
            "a target directory that does not exist yet must be created rather than skipped"
        )

    def test_first_run_reports_each_file_it_created(self, targets, capsys):
        sync.main([], targets=targets)
        printed = capsys.readouterr().out

        assert str(targets.opencode_home / "AGENTS.md") in printed, (
            "a run that writes a file must name that file"
        )
        assert "created" in printed, "a file that did not exist reports as created, not updated"

    def test_second_run_reports_no_change(self, targets, capsys):
        sync.main([], targets=targets)
        capsys.readouterr()

        sync.main([], targets=targets)
        printed = capsys.readouterr().out

        assert "created" not in printed and "updated" not in printed, (
            "generating twice from unchanged sources must be a no-op, or the output is not "
            "a function of the sources alone"
        )

    def test_check_exits_zero_when_every_output_matches(self, targets):
        sync.main([], targets=targets)

        assert sync.main(["--check"], targets=targets) == 0, (
            "a tree the generator just wrote is by definition up to date"
        )

    def test_check_exits_nonzero_after_a_source_changes(self, targets):
        sync.main([], targets=targets)
        _write(
            targets.claude_home / "rules" / "alpha.md", f"{_element('alpha', 'Alpha changed.')}\n"
        )

        assert sync.main(["--check"], targets=targets) != 0, (
            "an edited rule that never reached the generated files is what the push gate catches"
        )

    def test_check_exits_nonzero_when_an_output_is_missing(self, targets):
        assert sync.main(["--check"], targets=targets) != 0, (
            "a generated file that was never written differs from what a run would produce"
        )

    def test_check_writes_nothing(self, targets):
        sync.main(["--check"], targets=targets)

        assert not targets.pi_home.exists(), (
            "--check must be safe to run against a tree nobody intends to modify"
        )

    def test_check_leaves_a_stale_file_stale(self, targets):
        sync.main([], targets=targets)
        stale = targets.pi_home / "AGENTS.md"
        _write(stale, "hand-edited\n")

        sync.main(["--check"], targets=targets)

        assert stale.read_text(encoding="utf-8") == "hand-edited\n", (
            "--check reports a difference without repairing it"
        )


class TestRefusesToOverwriteUncommittedWork:
    def test_the_forward_direction_runs_against_a_clean_tree(self, committed):
        plan = sync.build_plan(committed)

        assert committed.working_rules in {generated.path for generated in plan.files}, (
            "a tree whose every change is committed has nothing a run could destroy"
        )

    def test_the_forward_direction_refuses_a_render_carrying_uncommitted_work(self, committed):
        _write(committed.working_rules, _reference(RENDERED_PREAMBLE, EDITED))

        with pytest.raises(ValueError, match=re.escape("working-rules.md")):
            sync.build_plan(committed)

    def test_the_forward_direction_runs_with_a_source_carrying_uncommitted_work(self, committed):
        _write(committed.rules_dir / "alpha.md", f"{EDITED}\n")

        built = sync.build_working_rules(
            committed.claude_md, committed.rules_dir, committed.working_rules_order
        )

        assert EDITED in built and sync.build_plan(committed).files, (
            "the source side is what this direction reads, and reading destroys nothing"
        )

    def test_the_reverse_direction_runs_against_a_clean_tree(self, committed):
        plan = sync.build_reverse_plan(committed)

        assert {generated.path for generated in plan.files} == {
            committed.claude_md,
            committed.rules_dir / "alpha.md",
        }, "a tree whose every change is committed has nothing a run could destroy"

    def test_the_reverse_direction_refuses_a_rules_file_carrying_uncommitted_work(self, committed):
        _write(committed.rules_dir / "alpha.md", f"{EDITED}\n")

        with pytest.raises(ValueError, match=re.escape("alpha.md")):
            sync.build_reverse_plan(committed)

    def test_the_reverse_direction_refuses_a_claude_md_carrying_uncommitted_work(self, committed):
        _write(
            committed.claude_md, f"{PREAMBLE}\n\n<what_wins>\n\nNearness decides.\n\n</what_wins>\n"
        )

        with pytest.raises(ValueError, match=re.escape("CLAUDE.md")):
            sync.build_reverse_plan(committed)

    def test_the_reverse_direction_runs_with_a_render_carrying_uncommitted_work(self, committed):
        _write(committed.working_rules, _reference(RENDERED_PREAMBLE, EDITED))

        files = {
            generated.path: generated.content
            for generated in sync.build_reverse_plan(committed).files
        }

        assert files[committed.rules_dir / "alpha.md"] == f"{EDITED}\n", (
            "an uncommitted render edit is the whole reason to run this direction"
        )

    def test_a_dirty_target_reports_every_file_it_would_have_overwritten(self, committed):
        _write(
            committed.claude_md, f"{PREAMBLE}\n\n<what_wins>\n\nNearness decides.\n\n</what_wins>\n"
        )
        _write(committed.rules_dir / "alpha.md", f"{EDITED}\n")

        with pytest.raises(ValueError) as raised:
            sync.build_reverse_plan(committed)

        assert "CLAUDE.md" in str(raised.value) and "alpha.md" in str(raised.value), (
            "a refusal naming one of two dirty files sends the reader back for the second"
        )

    def test_a_tree_outside_a_git_repository_runs(self, targets):
        assert sync.build_plan(targets).files, (
            "a checkout is not required, so configuration nobody versions still syncs"
        )


class TestDefaultTargets:
    def test_claude_home_is_the_checkout_the_script_lives_in(self):
        assert sync.DEFAULT_TARGETS.claude_home == REPO_ROOT, (
            "a run reads and writes the checkout it was invoked from, so a hook in a worktree "
            "syncs that worktree and needs no argument naming it"
        )

    def test_the_render_resolves_under_that_checkout(self):
        assert (
            sync.DEFAULT_TARGETS.working_rules == REPO_ROOT / "references" / "working-rules.md"
        ), "the render the pre-push gate compares is the one tracked beside the sources"


EDITED = _element("alpha", "Alpha holds, as edited in the render.")


class TestDirection:
    def test_no_argument_runs_the_forward_direction(self, targets):
        sync.main([], targets=targets)

        assert targets.working_rules.is_file(), (
            "the hooks call the script with no argument, and the render is what they expect"
        )

    def test_reverse_carries_a_render_edit_into_its_rules_file(self, targets):
        _write(targets.working_rules, _reference(RENDERED_PREAMBLE, EDITED))

        sync.main(["--reverse"], targets=targets)

        assert (targets.rules_dir / "alpha.md").read_text(encoding="utf-8") == f"{EDITED}\n", (
            "the render is the form the user edits, and the reverse is what carries those edits"
        )

    def test_reverse_leaves_the_render_as_it_found_it(self, targets):
        render = _reference(RENDERED_PREAMBLE, EDITED)
        _write(targets.working_rules, render)

        sync.main(["--reverse"], targets=targets)

        assert targets.working_rules.read_text(encoding="utf-8") == render, (
            "one run moves text one way, so the side it read from stands untouched"
        )

    def test_check_with_reverse_reports_a_pending_edit_and_writes_nothing(self, targets):
        _write(targets.working_rules, _reference(RENDERED_PREAMBLE, EDITED))
        untouched = (targets.rules_dir / "alpha.md").read_text(encoding="utf-8")

        assert sync.main(["--check", "--reverse"], targets=targets) != 0, (
            "a render edit that never reached its rules file is what this reports"
        )
        assert (targets.rules_dir / "alpha.md").read_text(encoding="utf-8") == untouched, (
            "--check reports a difference without repairing it, whichever direction it runs"
        )

    def test_check_with_reverse_exits_zero_when_the_sources_already_match(self, targets):
        _write(targets.working_rules, _reference(RENDERED_PREAMBLE, ALPHA))

        assert sync.main(["--check", "--reverse"], targets=targets) == 0, (
            "sources a reverse run would rewrite byte for byte are by definition up to date"
        )


class TestRoundTrip:
    def test_a_render_survives_a_reverse_then_a_forward_run(self, targets):
        render = _reference(RENDERED_PREAMBLE, EDITED)
        _write(targets.working_rules, render)

        sync.main(["--reverse"], targets=targets)
        rebuilt = sync.build_working_rules(
            targets.claude_md, targets.rules_dir, targets.working_rules_order
        )

        assert rebuilt == render, (
            "a render that does not come back byte for byte drifts a little on every sync"
        )

    def test_sources_survive_a_forward_then_a_reverse_run(self, targets):
        sources = [targets.claude_md, targets.rules_dir / "alpha.md"]
        before = {path: path.read_text(encoding="utf-8") for path in sources}

        sync.main([], targets=targets)
        sync.main(["--reverse"], targets=targets)

        assert {path: path.read_text(encoding="utf-8") for path in sources} == before, (
            "a source that does not come back byte for byte drifts a little on every sync"
        )

    def test_the_repository_render_survives_the_round_trip(self, tmp_path):
        original = (REPO_ROOT / "references" / "working-rules.md").read_text(encoding="utf-8")
        claude_home = tmp_path / "claude"
        _write(claude_home / "references" / "working-rules.md", original)
        targets = sync.Targets(
            claude_home=claude_home,
            pi_home=tmp_path / "pi",
            opencode_home=tmp_path / "opencode",
        )

        sync.main(["--reverse"], targets=targets)
        rebuilt = sync.build_working_rules(
            targets.claude_md, targets.rules_dir, targets.working_rules_order
        )

        assert rebuilt == original, (
            "the render this repository carries is the corpus the two directions run against, "
            "and a fixture that round trips proves nothing about it"
        )
