#!/usr/bin/env python3.14
"""Project Claude Code's canonical configuration onto pi and opencode.

A checkout carries `CLAUDE.md`, the rules under `rules/`, and the agent
definitions under `agents/`. This script reads the checkout it sits in,
resolved from its own path, so a hook running inside a worktree syncs that
worktree. pi and opencode read their own formats from their own directories,
and this script writes those, so the three agents run on the same behavioral
configuration and on whichever checkout last ran it.

`references/working-rules.md` renders `CLAUDE.md` and the always-on rules as
one document, in the order `WORKING_RULES_ORDER` names. That render and
those sources are two forms of one text, and this script moves between them
in either direction. With no argument it writes the render from the sources.
With `--reverse` it splits the render back into `CLAUDE.md` and the rules
files, writing no other output. One run moves text one way, and each
direction reproduces the other's input byte for byte.

Both directions read tag-form sources: `CLAUDE.md` opens on `<hello`, and
each rules file carries one `<rule name="stem">` element whose name is the
filename. A source in any other form stops the run before it writes.

Each direction writes its target side whole, so it refuses where a file it
would write carries changes git has not seen, naming each one. Commit those
changes and run again. No flag overrides the refusal.

`--check` compares without writing and exits nonzero where any output
differs from what a write would produce, which is what the pre-push hook
gates on. It composes with `--reverse`.

Every generated file is owned end to end: the script rewrites it whole and
never merges into hand-written content. One exception carries its own rule:
opencode's `instructions` array lists rule files rather than holding their
text, so it lives inside the hand-written `opencode.json`. The script owns
that one key and leaves every other key in the file as it found it.
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import os
import re
import subprocess
from pathlib import Path

import yaml

HOME = Path.home()

# The checkout this script sits in, so a run reads and writes the tree it was
# invoked from and a hook inside a worktree syncs that worktree.
SCRIPT_ROOT = Path(__file__).resolve().parents[1]

# Where generated content names a path, it names it through these rather than
# through HOME, so no generated byte carries the account the generator ran under.
HOME_VAR = "$HOME"
CLAUDE_HOME_VAR = f"{HOME_VAR}/.claude"


@dataclasses.dataclass(frozen=True)
class Document:
    """A markdown file split at its YAML frontmatter.

    `frontmatter` is None when the file opens on something other than a
    `---` line, which distinguishes a file carrying no frontmatter from one
    carrying an empty mapping.
    """

    frontmatter: dict | None
    body: str


FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)


def parse_document(text: str) -> Document:
    match = FRONTMATTER.match(text)
    if match is None:
        return Document(frontmatter=None, body=text)
    return Document(
        frontmatter=yaml.safe_load(match.group(1)) or {},
        body=text[match.end() :].lstrip("\n"),
    )


MARKDOWN_LINK = re.compile(r"(?<=\]\()([^)\s]+)(?=\))")
SCHEME = re.compile(r"\A[a-zA-Z][a-zA-Z0-9+.-]*:")


def _absolute_link_target(target: str) -> str:
    if target.startswith(("#", "/", "~", "$")) or SCHEME.match(target):
        return target
    return os.path.normpath(os.path.join(CLAUDE_HOME_VAR, target))


def rewrite_paths(text: str) -> str:
    """Resolve the path references that only work from inside `~/.claude`.

    Generated files sit in directories where `~` goes unexpanded and where a
    link relative to `~/.claude` points at nothing. Both forms resolve against
    `$HOME`, which names the same directory on any account; every other byte
    survives.
    """

    text = MARKDOWN_LINK.sub(lambda m: _absolute_link_target(m.group(1)), text)
    return text.replace("~/", f"{HOME_VAR}/")


def _relative_link_target(target: str) -> str:
    if not target.startswith(f"{HOME_VAR}/"):
        return target
    relative = os.path.relpath(target, CLAUDE_HOME_VAR)
    return relative if relative.startswith("..") else f"./{relative}"


def restore_paths(text: str) -> str:
    """Undo `rewrite_paths`, one inverse per step and in the same order.

    A source file sits inside `~/.claude`, where `~` expands and a link
    resolves against that directory. `_absolute_link_target` maps `./x`,
    `x`, and `~/.claude/x` onto one target, so this picks the `./` form,
    which is the one the sources carry.
    """

    text = MARKDOWN_LINK.sub(lambda m: _relative_link_target(m.group(1)), text)
    return text.replace(f"{HOME_VAR}/", "~/")


def all_rules(rules_dir: Path) -> list[Path]:
    """Every rule file, sorted by filename."""

    return sorted(rules_dir.glob("*.md"))


def unconditional_rules(rules_dir: Path) -> list[Path]:
    """The rule files that load every session, carrying no frontmatter.

    A rule carrying `paths:` frontmatter stays out. Claude Code loads one
    only once a matching file enters play, and each adapter reproduces that
    condition from the same frontmatter, so listing it here would put the
    text in every prompt and a second copy in a matching one.
    """

    return [
        rule
        for rule in all_rules(rules_dir)
        if parse_document(rule.read_text(encoding="utf-8")).frontmatter is None
    ]


def build_preamble(claude_md: Path) -> str:
    """`CLAUDE.md` alone, with its paths resolved."""

    return rewrite_paths(
        parse_document(claude_md.read_text(encoding="utf-8")).body.strip("\n") + "\n"
    )


def build_agents_markdown(claude_md: Path, rules_dir: Path) -> str:
    """Assemble the always-loaded configuration into one AGENTS.md body.

    pi reads one context file per directory and offers no second mechanism
    for carrying rules as separate files, so its copy holds the preamble and
    every rule concatenated, frontmatter stripped.
    """

    sections = [parse_document(claude_md.read_text(encoding="utf-8")).body]
    sections += [
        parse_document(rule.read_text(encoding="utf-8")).body
        for rule in unconditional_rules(rules_dir)
    ]
    return rewrite_paths("\n\n".join(section.strip("\n") for section in sections) + "\n")


WORKING_RULES_ORDER = (
    "core-rules",
    "reasoning-guidelines",
    "ask-user-before-assuming",
    "scope-is-user-decision",
    "claims",
    "epistemic-marks",
    "writing-prose",
    "writing-comments",
    "unasked-asides",
    "writing-code",
    "data-modeling",
    "repairing",
    "debugging",
    "search-tools",
    "reading-docs",
    "structural-search",
    "never-use-sed",
    "shell-quoting",
    "waiting-on-processes",
    "git-commit",
    "worktrees",
    "agent-delegation",
    "writing-plans",
    "scratchpad",
    "persistent-memory",
)

TITLE = "# Working Rules"

RULE_OPEN = re.compile(r'<rule name="([^"]+)">')
RULE_CLOSE = "</rule>"


@dataclasses.dataclass(frozen=True)
class RuleSection:
    """One `<rule>` element of the render, named by its `name` attribute.

    `text` carries the wrapper tags, so the section is what its rules file
    holds and nothing has to be rebuilt on the way in either direction.
    """

    name: str
    text: str


@dataclasses.dataclass(frozen=True)
class Reference:
    """`references/working-rules.md` split at its tag boundaries.

    `preamble` is what sits between the title and the first rule, which is
    what `CLAUDE.md` holds. The title belongs to the render alone.
    """

    preamble: str
    rules: tuple[RuleSection, ...]


def _fence_after(line: str, fence: str | None) -> str | None:
    """The fence state a line leaves behind, given the state it met."""

    stripped = line.lstrip()
    if fence is None:
        return stripped[:3] if stripped.startswith(("```", "~~~")) else None
    return None if stripped.startswith(fence) else fence


def parse_reference(text: str) -> Reference:
    """Split the render into its preamble and one section per rule.

    A `<rule>` tag inside a fenced block is a template a model copies, so
    only a tag outside every fence bounds a section.

    Raises ValueError where the document opens on something other than the
    title, where a rule never closes, where nothing precedes the first rule,
    or where a line sits outside every rule, since each of those would move
    text into a source file or drop it from one.
    """

    lines = text.split("\n")
    if lines[0] != TITLE:
        raise ValueError(f"the render must open on {TITLE!r}, not {lines[0]!r}")

    preamble: list[str] = []
    sections: list[RuleSection] = []
    body: list[str] = []
    open_name: str | None = None
    fence: str | None = None

    for line in lines[1:]:
        fence = _fence_after(line, fence)
        opening = RULE_OPEN.fullmatch(line) if fence is None else None
        if opening is not None:
            if open_name is not None:
                raise ValueError(f"rule {open_name!r} never closes before {opening.group(1)!r}")
            open_name = opening.group(1)
            body = [line]
            continue
        if open_name is None:
            if sections and line.strip():
                raise ValueError(f"this line sits outside every rule: {line!r}")
            preamble.append(line)
            continue
        body.append(line)
        if fence is None and line == RULE_CLOSE:
            sections.append(RuleSection(name=open_name, text="\n".join(body)))
            open_name = None

    if open_name is not None:
        raise ValueError(f"rule {open_name!r} never closes")

    joined = "\n".join(preamble).strip("\n")
    if not joined:
        raise ValueError("the render carries no preamble between its title and its first rule")
    return Reference(preamble=joined, rules=tuple(sections))


def ordered_rules(rules_dir: Path, order: tuple[str, ...]) -> list[Path]:
    """The unconditional rules in the given order.

    Raises ValueError naming every stem the order and the directory disagree
    on, so a new rule lands in the order before a run silently drops it.
    """

    present = {rule.stem: rule for rule in unconditional_rules(rules_dir)}
    unlisted = sorted(set(present) - set(order))
    absent = [stem for stem in order if stem not in present]
    if unlisted or absent:
        raise ValueError(
            f"working rules order disagrees with {rules_dir}: unlisted {unlisted}, absent {absent}"
        )
    return [present[stem] for stem in order]


PREAMBLE_OPEN = "<hello"


def _rule_form_fault(path: Path, body: str) -> str | None:
    """Whatever stops a rules file body from being one `<rule>` element."""

    lines = body.split("\n")
    opening = RULE_OPEN.fullmatch(lines[0])
    if opening is None or lines[-1] != RULE_CLOSE:
        return f"{path} carries no <rule> element"
    if opening.group(1) != path.stem:
        return f"{path} names itself {opening.group(1)!r}"
    return None


def build_working_rules(claude_md: Path, rules_dir: Path, order: tuple[str, ...]) -> str:
    """CLAUDE.md and the always-on rules as one document under its title.

    Raises ValueError naming every source that is not tag form, so a run
    against sources the reverse direction has not reached yet stops before
    `apply_plan` writes anything.
    """

    preamble = parse_document(claude_md.read_text(encoding="utf-8")).body.strip("\n")
    faults = (
        []
        if preamble.startswith(PREAMBLE_OPEN)
        else [f"{claude_md} does not open on {PREAMBLE_OPEN!r}"]
    )
    sections = [preamble]
    for rule in ordered_rules(rules_dir, order):
        body = parse_document(rule.read_text(encoding="utf-8")).body.strip("\n")
        fault = _rule_form_fault(rule, body)
        if fault is not None:
            faults.append(fault)
        sections.append(body)

    if faults:
        raise ValueError(
            "the render reads tag-form sources, and these are not: " + "; ".join(faults)
        )
    return rewrite_paths(f"{TITLE}\n\n" + "\n\n".join(sections) + "\n")


def rule_instructions(rules_dir: Path) -> list[str]:
    """The `instructions` entries opencode reads the session-wide rules from.

    Each names its canonical path under `~/.claude/rules/`, so an edit to a
    rule reaches opencode with no run of this script.
    """

    return [_home_relative(rule) for rule in unconditional_rules(rules_dir)]


def _home_relative(path: Path) -> str:
    """`~/`-prefixed where the path sits under the home directory, absolute otherwise."""

    return f"~/{path.relative_to(HOME)}" if path.is_relative_to(HOME) else str(path)


@dataclasses.dataclass(frozen=True)
class AgentDefinition:
    """One Claude Code agent definition, read from `agents/<name>.md`.

    `model` is None where the source names none, which means the agent
    inherits its caller's model. `tools` is None where the source names
    none, which grants every tool rather than no tool.
    """

    name: str
    description: str
    model: str | None
    tools: tuple[str, ...] | None
    body: str


@dataclasses.dataclass(frozen=True)
class Translation:
    """A generated agent file, with the source tool names it could not carry."""

    content: str
    dropped: tuple[str, ...]


def read_agent(path: Path) -> AgentDefinition:
    document = parse_document(path.read_text(encoding="utf-8"))
    frontmatter = document.frontmatter or {}
    tools = frontmatter.get("tools")
    return AgentDefinition(
        name=frontmatter["name"],
        description=frontmatter["description"],
        model=frontmatter.get("model"),
        tools=None if tools is None else tuple(t.strip() for t in tools.split(",") if t.strip()),
        body=document.body,
    )


OPENCODE_MODEL_IDS = {
    "haiku": "anthropic/claude-haiku-4-5",
    "sonnet": "anthropic/claude-sonnet-4-6",
    "opus": "anthropic/claude-opus-4-7",
}

OPENCODE_TOOL_NAMES = {
    "Read": "read",
    "Write": "write",
    "Edit": "edit",
    "Bash": "bash",
    "Grep": "grep",
    "Glob": "glob",
    "Agent": "task",
}

PI_TOOL_NAMES = {
    "Read": "read",
    "Write": "write",
    "Edit": "edit",
    "Bash": "bash",
    "Grep": "grep",
    "Glob": "find",
}


def _map_tools(
    tools: tuple[str, ...] | None, names: dict[str, str]
) -> tuple[list[str] | None, tuple[str, ...]]:
    if tools is None:
        return None, ()
    mapped = [names[tool] for tool in tools if tool in names]
    dropped = tuple(tool for tool in tools if tool not in names)
    return mapped, dropped


def _render(frontmatter: dict, body: str) -> str:
    rendered = yaml.safe_dump(
        frontmatter,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=10**9,
    )
    return f"---\n{rendered}---\n\n{body}"


def translate_for_opencode(agent: AgentDefinition) -> Translation:
    frontmatter: dict = {"description": agent.description, "mode": "subagent"}
    if agent.model is not None:
        frontmatter["model"] = OPENCODE_MODEL_IDS[agent.model]
    tools, dropped = _map_tools(agent.tools, OPENCODE_TOOL_NAMES)
    if tools is not None:
        frontmatter["tools"] = dict.fromkeys(tools, True)
    return Translation(content=_render(frontmatter, agent.body), dropped=dropped)


def translate_for_pi(agent: AgentDefinition) -> Translation:
    frontmatter: dict = {"description": agent.description}
    if agent.model is not None:
        frontmatter["model"] = agent.model
    tools, dropped = _map_tools(agent.tools, PI_TOOL_NAMES)
    if tools is not None:
        frontmatter["tools"] = ", ".join(tools)
    frontmatter["inheritSkills"] = True
    return Translation(content=_render(frontmatter, agent.body), dropped=dropped)


def _install_path(records: list[dict]) -> str | None:
    """Pick the one install a user-level enable turns on.

    A plugin installed against several projects can carry several versions
    at once. Putting all of them on a skills path loads each skill twice
    under two versions, so the user-scoped record wins where one exists.
    """

    for record in records:
        if record.get("scope") == "user":
            return record.get("installPath")
    return records[0].get("installPath") if records else None


def resolve_skill_paths(installed_plugins: Path, settings: Path) -> list[str]:
    plugins = json.loads(installed_plugins.read_text(encoding="utf-8")).get("plugins", {})
    enabled = json.loads(settings.read_text(encoding="utf-8")).get("enabledPlugins", {})

    resolved = set()
    for key, is_enabled in enabled.items():
        if not is_enabled:
            continue
        install_path = _install_path(plugins.get(key, []))
        if install_path is None:
            continue
        skills = Path(install_path) / "skills"
        if skills.is_dir():
            resolved.add(str(skills))
    return sorted(resolved)


@dataclasses.dataclass(frozen=True)
class Targets:
    """The three roots this script reads from and writes to."""

    claude_home: Path
    pi_home: Path
    opencode_home: Path
    working_rules_order: tuple[str, ...] = WORKING_RULES_ORDER

    @property
    def claude_md(self) -> Path:
        return self.claude_home / "CLAUDE.md"

    @property
    def working_rules(self) -> Path:
        return self.claude_home / "references" / "working-rules.md"

    @property
    def rules_dir(self) -> Path:
        return self.claude_home / "rules"

    @property
    def agents_dir(self) -> Path:
        return self.claude_home / "agents"

    @property
    def installed_plugins(self) -> Path:
        return self.claude_home / "plugins" / "installed_plugins.json"

    @property
    def settings(self) -> Path:
        return self.claude_home / "settings.json"

    @property
    def skill_paths_file(self) -> Path:
        return self.claude_home / "scratchpad" / "main" / "generated-skill-paths.json"

    @property
    def opencode_config(self) -> Path:
        return self.opencode_home / "opencode.json"


DEFAULT_TARGETS = Targets(
    claude_home=SCRIPT_ROOT,
    pi_home=HOME / ".pi" / "agent",
    opencode_home=HOME / ".config" / "opencode",
)


@dataclasses.dataclass(frozen=True)
class GeneratedFile:
    path: Path
    content: str


@dataclasses.dataclass(frozen=True)
class GeneratedKey:
    """One top-level key this script owns inside a hand-written JSON file.

    `after` names the key the new one follows when the file carries none
    yet, so a first write lands where a reader expects it rather than at the
    end. Every other key, and the file's key order, survives the write.
    """

    path: Path
    key: str
    value: object
    after: str


@dataclasses.dataclass(frozen=True)
class Plan:
    """Every file a run would write, and every tool grant that could not cross.

    `dropped` holds (target, agent, tool) for each source tool name the
    target has no equivalent for, so a run reports where an agent's reach
    narrowed rather than narrowing it silently.
    """

    files: tuple[GeneratedFile, ...]
    keys: tuple[GeneratedKey, ...]
    dropped: tuple[tuple[str, str, str], ...]


def uncommitted(repo: Path, paths: list[Path]) -> list[str]:
    """Whichever of `paths` git reports as changed in `repo`.

    A directory outside any git repository reports none, so a run still
    works where nobody versions the configuration.
    """

    if not paths:
        return []
    finished = subprocess.run(
        ["git", "-C", str(repo), "status", "--porcelain", "--", *(str(path) for path in paths)],
        capture_output=True,
        text=True,
        check=False,
    )
    if finished.returncode != 0:
        return []

    changed = []
    for line in finished.stdout.splitlines():
        # Porcelain v1 gives two status characters, a space, then the path,
        # and a rename gives "old -> new", where the new name is the target.
        named = line[3:]
        _, _, renamed = named.partition(" -> ")
        changed.append(renamed or named)
    return changed


def refuse_uncommitted(repo: Path, paths: list[Path]) -> None:
    """Stop a run that would write over changes nobody has committed.

    Each direction overwrites the side it writes to whole, so a target
    carrying an edit git has never seen loses that edit with no diff to
    recover it from.
    """

    changed = uncommitted(repo, paths)
    if changed:
        raise ValueError(
            "these carry uncommitted changes this run would overwrite: "
            + ", ".join(changed)
            + ". Commit them and run again."
        )


def build_plan(targets: Targets = DEFAULT_TARGETS) -> Plan:
    refuse_uncommitted(targets.claude_home, [targets.working_rules])
    files = [
        GeneratedFile(
            targets.pi_home / "AGENTS.md",
            build_agents_markdown(targets.claude_md, targets.rules_dir),
        ),
        GeneratedFile(targets.opencode_home / "AGENTS.md", build_preamble(targets.claude_md)),
        GeneratedFile(
            targets.working_rules,
            build_working_rules(targets.claude_md, targets.rules_dir, targets.working_rules_order),
        ),
    ]
    keys = [
        GeneratedKey(
            targets.opencode_config,
            "instructions",
            rule_instructions(targets.rules_dir),
            after="$schema",
        )
    ]
    dropped: list[tuple[str, str, str]] = []

    for source in sorted(targets.agents_dir.glob("*.md")):
        agent = read_agent(source)
        for label, home, translate in (
            ("opencode", targets.opencode_home, translate_for_opencode),
            ("pi", targets.pi_home, translate_for_pi),
        ):
            translated = translate(agent)
            files.append(GeneratedFile(home / "agents" / f"{source.stem}.md", translated.content))
            dropped += [(label, source.stem, tool) for tool in translated.dropped]

    skill_paths = resolve_skill_paths(targets.installed_plugins, targets.settings)
    files.append(
        GeneratedFile(
            targets.skill_paths_file,
            json.dumps({"paths": skill_paths}, indent=2) + "\n",
        )
    )
    return Plan(files=tuple(files), keys=tuple(keys), dropped=tuple(dropped))


def _carries_frontmatter(path: Path) -> bool:
    return (
        path.is_file() and parse_document(path.read_text(encoding="utf-8")).frontmatter is not None
    )


def build_reverse_plan(targets: Targets = DEFAULT_TARGETS) -> Plan:
    """Every source file a run in the reverse direction would write.

    The render is the form the user edits, and this carries those edits back
    into `CLAUDE.md` and the rules files it was rendered from.

    Raises ValueError where the render's rules and `working_rules_order`
    disagree, so a rule added to the render lands its stem in the order in
    the same change, and where a rule resolves to a file carrying
    frontmatter, since that frontmatter is what scopes a rule to its paths.
    """

    reference = parse_reference(targets.working_rules.read_text(encoding="utf-8"))
    named = tuple(section.name for section in reference.rules)
    if named != targets.working_rules_order:
        raise ValueError(
            f"the render's rules disagree with the order: render {list(named)}, "
            f"order {list(targets.working_rules_order)}"
        )

    written = [targets.claude_md] + [
        targets.rules_dir / f"{section.name}.md" for section in reference.rules
    ]
    refuse_uncommitted(targets.claude_home, written)

    files = [GeneratedFile(targets.claude_md, restore_paths(reference.preamble) + "\n")]
    for section in reference.rules:
        path = targets.rules_dir / f"{section.name}.md"
        if _carries_frontmatter(path):
            raise ValueError(f"{path} carries frontmatter, which scopes it to its own paths")
        files.append(GeneratedFile(path, restore_paths(section.text) + "\n"))
    return Plan(files=tuple(files), keys=(), dropped=())


def _reorder(data: dict, key: str, value: object, after: str) -> dict:
    """`data` with `key` set to `value`, placed after `after` when new."""

    if key in data:
        return {name: (value if name == key else held) for name, held in data.items()}
    reordered: dict = {}
    for name, held in data.items():
        reordered[name] = held
        if name == after:
            reordered[key] = value
    if key not in reordered:
        reordered[key] = value
    return reordered


def _current(path: Path) -> str | None:
    return path.read_text(encoding="utf-8") if path.is_file() else None


def apply_plan(plan: Plan, *, check: bool) -> int:
    stale = 0
    for generated in plan.files:
        current = _current(generated.path)
        if current == generated.content:
            continue
        stale += 1
        if check:
            state = "missing" if current is None else "stale"
            print(f"{state}: {generated.path}")
            continue
        generated.path.parent.mkdir(parents=True, exist_ok=True)
        generated.path.write_text(generated.content, encoding="utf-8")
        if current is None:
            print(f"created: {generated.path} ({len(generated.content.encode())} bytes)")
        else:
            print(
                f"updated: {generated.path} "
                f"({len(current.encode())} -> {len(generated.content.encode())} bytes)"
            )

    for owned in plan.keys:
        # A config file absent altogether gets created holding this key
        # alone, so a fresh machine needs no hand-written stub first.
        data = json.loads(owned.path.read_text(encoding="utf-8")) if owned.path.is_file() else {}
        if data.get(owned.key) == owned.value:
            continue
        stale += 1
        if check:
            state = "missing" if owned.key not in data else "stale"
            print(f"{state}: {owned.key} in {owned.path}")
            continue
        rewritten = _reorder(data, owned.key, owned.value, owned.after)
        owned.path.parent.mkdir(parents=True, exist_ok=True)
        owned.path.write_text(json.dumps(rewritten, indent=2) + "\n", encoding="utf-8")
        print(f"updated: {owned.key} in {owned.path}")

    for label, agent, tool in plan.dropped:
        print(f"dropped: {tool} from {agent} for {label}, which carries no equivalent")

    total = len(plan.files) + len(plan.keys)
    if check:
        print(f"{stale} of {total} generated outputs out of date")
        return 1 if stale else 0
    print(f"{stale} of {total} generated outputs written")
    return 0


def main(argv: list[str] | None = None, targets: Targets = DEFAULT_TARGETS) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit nonzero when any generated file is out of date",
    )
    parser.add_argument(
        "--reverse",
        action="store_true",
        help="split the render back into CLAUDE.md and the rules files, writing no other output",
    )
    args = parser.parse_args(argv)
    build = build_reverse_plan if args.reverse else build_plan
    return apply_plan(build(targets), check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
